### ISSUE TITLE
Property "password" does not works on android

### ISSUE THREAD

**Issue by koraniar** [mayank-patel/react-native-floating-labels#13]
React Native 0.39.2
Android 7.1.1 & 6.0.1 & 5.1
IOS 10.2

IOS : 
![ios](https://cloud.githubusercontent.com/assets/17574419/22209522/c7c2508e-e154-11e6-9763-93503bc85dd4.png)

Android : 
![android](https://cloud.githubusercontent.com/assets/17574419/22209537/d69ab1a0-e154-11e6-86f3-698e977144b5.png)

My code

```
import FloatingLabel from 'react-native-floating-labels';

<FloatingLabel
            labelStyle={styles.labelInput}
            inputStyle={styles.input}
            password={true}
            onChangeText={(e) => EmployerData.password = e.trim().replace('+', encodeURIComponent('+'))}
            style={[styles.formInput, styles.textfieldWithFloatingLabel, { marginTop: mainComponent.state.marginBetweenFields, borderColor: mainComponent.state.underlineColor }]}>Contraseña</FloatingLabel>
```

This code works properly on IOS but on Android the letters are not hiding,
I had test it on Android 7.1.1 (Nougat), 6.0.1 (Marshmallow), 5.1 (lollipop)

**Comment by karaxuna** [comment]
https://github.com/mayank-patel/react-native-floating-labels/pull/14
